name: Folder check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: GithubInfo
        run: echo '${{ toJSON(github) }}'

      # Updates the readme file (hopefully)
      - name: FolderCheck
        run: python FolderCheck.py -fc "${{ github.event.head_commit }}"
      
      # - name: Commit files
      #   uses: EndBug/add-and-commit@v7.5.0
      #   with:
      #     message: "File checker ++skip"
      #     author_name: "FC"
